### PR TITLE
Symlink and unittest

### PR DESCRIPTION
**Pull request by if1live**
I split single commit to many commits
- support python 3 (python3's importing is different with python2)
- add symbolic link module (support create, readlink, is symbolic link)
- add unit test
- modify reparse data buffer to reuse in junction, symbolic link
  - modify type of SubstituteNameBuffer : from wchar to ushort
  - name of symbolic link contains `\0`. so normal string is not useful this case.
  - add function to print reparse data buffer. for debugging

### CODE REVIEW

**Comment by sid0** [comment]
Looks OK overall -- but the issues in the inline comments need to be addressed before this can land. Thanks!

**Comment by if1live** [comment]
@sid0 wold you review my pull request again?

**Comment by sid0** [comment]
BTW, please clean up your commits so that each commit individually makes sense. I don't want separate commits with review feedback addressed -- you can use `git rebase -i` or similar to reorder squash commits. The overall goal is to make it so that the overall history makes sense for someone coming in 5 years down the line, going through old history. This is because the number of people reading a bit of code is orders of magnitude higher than the number of people writing it.

**Comment by if1live** [comment]
I add a CI service to use unit test.
Supporting python 2.x/3.x is too hard without CI.
https://ci.appveyor.com/project/if1live/ntfs

**Comment by sid0** [comment]
Cool, thanks. (I'd known about Appveyor but have been too busy/lazy to set it up. I'll probably do it now. I'll review your patches either today or tomorrow. Thanks again.

**Comment by sid0** [comment]
Oh wow, I completely forgot about this among a bunch of other work I've been doing. I'm going to try and spare some time today to land this. Thanks for your patience.

**Comment by remyroy** [comment]
It would be nice if this was reviewed and included in an updated release of ntfsutils. There would be some uses for me in my project.

**Comment by sid0** [comment]
I spent a fair amount of time looking at this today and it the series still doesn't really make sense. There are way too many things mixed up here:

* supporting Python 3
* adding unit tests
* adding appveyor CI
* adding symlink support

Someone is going to have to clean this up and present this as a series of self-contained commits that make sense (and should individually work so that bisect works).

Unfortunately I have no time to look at this in the short to midterm future. @if1live, @remyroy or anyone else who is interested in getting it in -- it's up to you.

**Comment by sid0** [comment]
Closing this because of lack of a response. PRs for symlink support are still welcome, but please read [this earlier comment](https://github.com/sid0/ntfs/pull/8#issuecomment-168241345) before proceeding.

**Pull request closed without merging**
